config/routes.rb
Rails.application.routes.draw do
  
  resources :reports
  root "league#edit"

  resources :users, except: [:destroy, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get '/login'  => "sessions#new", as: :login
  post '/login' => "sessions#create"
  post 'logout'  => "sessions#destroy", as: :logout


  resources :league
  resources :players
  resources :teams
end

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/league.rb
class League < ActiveRecord::Base
	validates :name, presence: true

  has_many :teams

end

app/controllers/league_controller.rb
class LeagueController < ApplicationController
  
  def index
    @league=League.all 

  end

  def new
  @league = League.new(params[:name])
  
  end  



  def create
     @league = League.new(league_params)
    if @league.save
      redirect_to :league, notice: "Success"
    else
      flash.now[:alert] = "Couldn't save"
      render :new
    end
  end

  def show
    @player = Player.all
    @league = League.find(params[:id])
    @players = Player.all
  end

  def update
    @league = League.find(params[:id])
    if @league.update_attributes(league_params)
      redirect_to league_path(@league), notice: "Successfully Updated!!!!"
    else
      flash.now[:alert]="Couldn't update."
      render :edit
    end
  end

  def edit
    @league = League.find(params[:id])

  end

  def destroy
    @team = League.find(params[:name])
    @team.destroy
    redirect_to :league, notice: "Successfully deleted!!!"
  end


private
 def league_params
       params.require(:league).permit(:name)
 end

end

app/helpers/league_helper.rb
module LeagueHelper
end

app/views/league/create.html.erb
<h1>League#create</h1>
<p>Find me in app/views/league/create.html.erb</p>

app/views/league/destroy.html.erb
<h1>League#destroy</h1>
<p>Find me in app/views/league/destroy.html.erb</p>

app/views/league/edit.html.erb
<h1>League#edit</h1>
<p>Find me in app/views/league/edit.html.erb</p>

app/views/league/index.html.erb
<style>
h1 {text-align:center;}
.list {text-align:left;
				color: black;}
a {
    color: #ECFD30;

}
a:link, a:visited {
    background-color: #ECFD30;
    color: black;
    padding: 8px 25px;
    text-align: center; 
    text-decoration: none;
    display: inline-block;
    border-radius: 15px
}
</style>
<body>
<h1><font size="24">Lincoln Nebraska Soccer League</font></h1>

<div class= "list">
    <p><a><%= link_to "Current Teams", :teams %></a></p>
    <p><a><%= link_to "Current Players", :players %></a></p>
</body>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
		<p><a href="/reports">contact us</a></p>

</div>

app/views/league/new.html.erb
<h1>Create New League</h1>

<%= form_for @league do |t| %>
  <%= t.label :name %>:<br>

  <%= t.text_field :name %>:

  <%= t.submit %>
<% end %>

app/views/league/show.html.erb
<h5>This is the <%= @league.name %> League</h5>


<h1><%= @league.name %></h1>





  <div class="input-field col xs12 sr12 m12">
<!-- add player to team -->
    <select class="icons" id="league" name="league_id">
      <option value="" disabled selected>Add Team to League</option>
      <% @teams.each do |t| %>
        <option value="<%= t.id %>" 
          <span class="left"><%= t.name %></span>
        </option>
      <% end %>
    </select>
    <br>
    <br>
    <%= render "form" %>
    <label></label>
  </div><br><br>







<p><%= link_to "Edit Team", edit_team_path(@team) %></p>
<p><%= link_to "All Teams", :teams %></p>

app/views/league/update.html.erb
<h1>League#update</h1>
<p>Find me in app/views/league/update.html.erb</p>