config/routes.rb
Rails.application.routes.draw do
  
  resources :reports
  root "league#edit"

  resources :users, except: [:destroy, :edit, :update]
  resources :sessions, only: [:new, :create, :destroy]

  get '/login'  => "sessions#new", as: :login
  post '/login' => "sessions#create"
  post 'logout'  => "sessions#destroy", as: :logout


  resources :league
  resources :players
  resources :teams
end

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :name, presence: true

  belongs_to :team
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  
  def index
    @players = Player.all
    @team = Team.all
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to :players, notice: "Success"
    else
      flash.now[:alert] = "Couldn't save"
      render :new
    end
  end

  def show
    @player = Player.find(params[:id])
    @team = Team.all

  end

  def update
    @player = Player.find(params[:id])
    if @player.update_attributes(player_params)
      redirect_to player_path(@player), notice: "Successfully Updated!!!!"
    else
      flash.now[:alert]="Couldn't update."
      render :edit
    end
  end

  def edit
    @player = Player.find(params[:id])
    @team = Team.all

  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to :players, notice: "Successfully deleted!!!"
  end

   private
 def player_params
       params.require(:player).permit(:name, :team_id, :email, :team_name)
 end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for @player do |f| %>

<div>
<% if f.object.errors.any?%>
    <% f.object.errors.full_messages.each do |x|%>
      <li>Error: <%= x %></li>
    <% end %>
      <li>Player info was not saved</li>
  <% end %>
  </div>

  <div>
    <div>
      <%= f.label :name %>
    </div>
    <div>
      <%= f.text_field :name %>
    </div>
  </div>

  <div>
    <br>
    <%= f.label :team_id, "team name" %>
      <div class="input-field">
        <%= f.select(:team_id) do %>
          <% teams_array = Team.all.map { |team| [team.name, team.id] } %>
          <%= options_for_select(teams_array) %>
        <% end %>
      </div>
  </div>

  <div>
    <br>
      <div>
        <%= f.label :email %>
      </div>
      <div>
        <%= f.text_field :email %>
      </div>
  </div>

  <div>
    <br>
      <%= f.submit %>
  </div>
  <% end %>

app/views/players/create.html.erb
<h1>Players create</h1>

app/views/players/destroy.html.erb
<h1>Players destroy</h1>

app/views/players/edit.html.erb
<h1>Players edit</h1>

<div class= "container">
	<h5>Edit <%=@player.name%></h5>

	<%= render "form" %>
</div>

<p><%= link_to "All Players", :players %></p>
<p><a href="/reports">Interested in more information about the league?</a></p>

app/views/players/index.html.erb
<style>
a {
    color: #ECFD30;

}
</style>

<h1>League Player Index</h1>
      <div class= "number-teams">
			<h3>There are <%= Player.count %> Players In the Lincoln, Nebraska Soccer League</h3>
</div1>

<div>
	<% if flash[:notice] %>
	  <div class="flash notice row">
	    <p><%= flash[:notice] %></p>
	  </div>
	<% end %>
</div>

<div class="container">
<div class= "players-list"
   <% if @players.any? %>
    <% @players.each do |p| %>
    <li class="block">
      <p><a>Name:  <%= link_to p.name, player_path(p) %></a></p>
      <p>Team:  <%= p.team.name if p.team %></p>
      <p>Email: <%= p.email %></p>
      </li>
  <% end %>
  <% end %>
</div>
</div>

<br>
<p><%= link_to "All Players", :players %></p>
<br>
<p><%= link_to "All Teams", :teams%></p>
<br>
<div class= "button-link"
<p><a href="/league">Back Home</a></p>
<p><a href="/reports">Interested in more information about the league?</a></p>

app/views/players/new.html.erb
<h1>New Player Registration</h1>
<style>
a {
    color: #ECFD30;

}
</style>

<div class="container">

	<%= render "form" %>
</div>


<p><a><%= link_to "All Players", :players %></a></p>

<br>
<p><%= link_to "All Teams", :teams %></p>
<br>
<p><a href="/league">Back Home</a></p>

<p><a href="/reports">Interested in more information about the league?</a></p>

app/views/players/show.html.erb
<body>
<h1></h1>

<h1><%= @player.name %></h1>
<br>
<br>
<% if flash[:notice] %>
  <div class="flash notice">
    <p><%= flash[:notice] %></p>
  </div>
<% end %>

<div>
<p>Team:  <%= @player.team.name if @player.team %></p>
<p>Email: <%= @player.email %></p>
</div>




<p><%= link_to "Edit Player", edit_player_path(@player) %></p>
<br>
<p><%= link_to "All Players", :players %></p>
<br>
<p><a href="/league">Back Home</a></p>
<p><a href="/reports">Interested in more information about the league?</a></p>

<body/>

app/views/players/update.html.erb
<h1>Players update</h1>